# AQ_Net2 Project Configuration
# Training settings
train:
  epochs: 8
  batch_size: 8          # Réduit pour embed_dim=1024
  learning_rate: 0.0001
  patience: 5

# Data configuration
data:
  data_path: "/scratch/project_462000640/ammar/data_aq_net2/"
  checkpoint_path: "checkpoints/climax_1.40625deg.ckpt"
  train_years: [2013, 2014, 2015]
  val_years: [2016, 2017]
  test_years: [2018]
  variables: ['u', 'v', 'temp', 'rh', 'psfc', 'pm10', 'so2', 'no2', 'co', 'o3']
  target_variables: ['pm25']
  # Temporal settings - Optimisé pour mémoire
  time_step: 1          # in hours
  # history_days: 0  # Not used in this new approach       # Réduit de 7 à 2 jours (48h)
  forecast_days: [1, 3, 5, 7] # Multi-horizon in days      # Réduit de 3 à 1 jour (24h) 
  
  normalize: true
  target_resolution: [128, 256]

# Model configuration
model:
  img_size: [128, 256]
  patch_size: 4
  embed_dim: 1024       # Retour à 1024 pour les poids pré-entraînés
  depth: 8
  decoder_depth: 2
  num_heads: 16
  mlp_ratio: 4
  drop_path: 0.1
  drop_rate: 0.1

# System configuration
system:
  miopen_cache_dir: "/scratch/project_462000640/ammar/miopen_cache"
  num_workers: 0
